# syntax=docker/dockerfile:1.7

ARG RUST_VERSION=1.85
FROM docker.io/library/rust:${RUST_VERSION}-bookworm AS rust-builder

WORKDIR /src
COPY Cargo.toml Cargo.lock rust-toolchain.toml ./
COPY crates ./crates
RUN cargo build --release --locked --bin andromeda --bin andromeda-taskd

FROM quay.io/fedora/fedora-bootc:44 AS payload

RUN dnf -y install \
        NetworkManager \
        curl \
        firewalld \
        jq \
        linux-firmware \
        openssh-server \
        podman \
        qemu-guest-agent \
        skopeo \
        sudo \
    && dnf clean all \
    && rm -rf /var/cache/dnf

RUN dnf -y install \
        mesa-dri-drivers \
        mesa-vulkan-drivers \
        vulkan-loader \
    && dnf clean all \
    && rm -rf /var/cache/dnf

RUN dnf -y install \
        wireplumber \
    && dnf clean all \
    && rm -rf /var/cache/dnf

RUN dnf -y install \
        sddm \
    && dnf clean all \
    && rm -rf /var/cache/dnf

RUN dnf -y install \
        kwin \
    && dnf clean all \
    && rm -rf /var/cache/dnf

RUN dnf -y install \
        plasma-desktop \
        plasma-nm \
        plasma-workspace \
        xdg-desktop-portal-kde \
    && dnf clean all \
    && rm -rf /var/cache/dnf

RUN dnf -y install \
        dolphin \
        konsole \
    && dnf clean all \
    && rm -rf /var/cache/dnf

RUN dnf -y install \
        ark \
        ffmpegthumbs \
        gwenview \
        kcalc \
        kate \
        kdegraphics-thumbnailers \
        kinfocenter \
        kio-extras \
        okular \
        plasma-pa \
        plasma-systemmonitor \
        spectacle \
        xorg-x11-server-Xwayland \
    && dnf clean all \
    && rm -rf /var/cache/dnf

RUN dnf -y install \
        flatpak \
        fedora-flathub-remote \
        plasma-discover \
        plasma-discover-flatpak \
        qt6-qtwayland \
        xdg-desktop-portal \
        xdg-desktop-portal-gtk \
    && dnf clean all \
    && rm -rf /var/cache/dnf

RUN dnf -y install \
        pipewire \
        pipewire-alsa \
        pipewire-pulseaudio \
        pipewire-utils \
        wireplumber \
    && dnf clean all \
    && rm -rf /var/cache/dnf

RUN dnf -y install \
        alsa-sof-firmware \
        bluez \
        bluez-obexd \
        bluedevil \
        bolt \
        cups \
        cups-filters \
        fprintd \
        fwupd \
        libcamera-tools \
        powerdevil \
        sane-backends \
        system-config-printer \
        thermald \
        upower \
    && dnf clean all \
    && rm -rf /var/cache/dnf

RUN dnf -y install \
        libreoffice-calc \
        libreoffice-draw \
        libreoffice-impress \
        libreoffice-writer \
        poppler-utils \
        unzip \
    && dnf clean all \
    && rm -rf /var/cache/dnf

RUN dnf -y install \
        7zip \
        fcitx5 \
        fcitx5-autostart \
        fcitx5-chinese-addons \
        fcitx5-gtk \
        fcitx5-qt \
        ffmpeg-free \
        google-noto-color-emoji-fonts \
        gstreamer1-plugins-bad-free \
        gstreamer1-plugins-base \
        gstreamer1-plugins-good \
        gstreamer1-plugins-ugly-free \
        hunspell \
        hunspell-en \
        liberation-fonts-all \
        unar \
    && dnf clean all \
    && rm -rf /var/cache/dnf

RUN dnf -y install \
        gamemode \
        gamescope \
        mangohud \
        mesa-dri-drivers.i686 \
        mesa-vulkan-drivers.i686 \
        steam-devices \
        vulkan-loader.i686 \
    && dnf clean all \
    && rm -rf /var/cache/dnf

RUN dnf -y install \
        systemd-oomd-defaults \
        zram-generator-defaults \
    && dnf clean all \
    && rm -rf /var/cache/dnf

RUN dnf -y install \
        firewall-config \
    && dnf clean all \
    && rm -rf /var/cache/dnf

RUN dnf -y install \
        firefox \
    && dnf clean all \
    && rm -rf /var/cache/dnf

RUN dnf -y install \
        glibc-langpack-en \
        glibc-langpack-zh \
    && dnf clean all \
    && rm -rf /var/cache/dnf

COPY --from=rust-builder /src/target/release/andromeda /usr/bin/andromeda
COPY --from=rust-builder /src/target/release/andromeda-taskd /usr/bin/andromeda-taskd
COPY os/files/ /

ARG IMAGE_REVISION=1

RUN mkdir -p /usr/lib/andromeda \
    && printf '%s\n' "${IMAGE_REVISION}" > /usr/lib/andromeda/image-revision \
    && systemctl disable sshd.service \
    && systemctl enable \
        NetworkManager.service \
        andromeda-first-boot-labels.service \
        andromeda-hardware-report.service \
        andromeda-taskd.service \
        andromeda-ci-verify.service \
        bluetooth.service \
        cups.service \
        firewalld.service \
        fstrim.timer \
        qemu-guest-agent.service \
        sddm.service \
        systemd-oomd.service \
    && systemctl set-default graphical.target \
    && bootc container lint

FROM payload AS installer

ARG INSTALLER_DEFAULT=0

RUN dnf -y install \
        anaconda \
        anaconda-dracut \
        anaconda-install-img-deps \
        default-fonts-core-sans \
        default-fonts-other-sans \
        dracut-config-generic \
        dracut-network \
        efibootmgr \
        google-noto-sans-cjk-fonts \
        grub2-efi-x64 \
        grub2-efi-x64-cdboot \
        net-tools \
        plymouth \
        shim-x64 \
        squashfs-tools \
        xorrisofs \
    && dnf clean all \
    && rm -rf /var/cache/dnf \
    && mkdir -p /boot/efi \
    && cp -ra /usr/lib/efi/*/*/EFI /boot/efi

COPY os/installer/iso.yaml /usr/lib/image-builder/bootc/iso.yaml
COPY os/installer/interactive-defaults.ks /usr/share/anaconda/interactive-defaults.ks
COPY os/installer/andromeda-ci.ks /usr/share/anaconda/andromeda-ci.ks
COPY os/installer/install-uefi-fallback.sh /usr/libexec/andromeda-install-uefi-fallback
COPY os/installer/installer-preflight.sh /usr/libexec/andromeda-installer-preflight
COPY os/installer/collect-anaconda-diagnostics.sh /usr/libexec/andromeda-collect-anaconda-diagnostics

RUN sed -i "s/^  default: 0$/  default: ${INSTALLER_DEFAULT}/" \
        /usr/lib/image-builder/bootc/iso.yaml \
    && anaconda_version="$(rpm -q --qf '%{VERSION}\n' anaconda-core)" \
    && test "${anaconda_version%%.*}" -ge 44 \
    && printf 'Validated Anaconda %s with native bootc payload support.\n' \
        "${anaconda_version}" \
    && bootc --version \
    && test -f /boot/efi/EFI/fedora/shimx64.efi \
    && test -f /boot/efi/EFI/fedora/grubx64.efi \
    && test -f /boot/efi/EFI/fedora/mmx64.efi \
    && test -f /boot/efi/EFI/fedora/gcdx64.efi \
    && printf '%s\n' \
        'install:x:0:0:root:/root:/usr/libexec/anaconda/run-anaconda' \
        >> /etc/passwd \
    && printf '%s\n' 'install::14438:0:99999:7:::' >> /etc/shadow \
    && passwd -d root \
    && mv /usr/share/anaconda/list-harddrives-stub /usr/bin/list-harddrives \
    && mv /etc/yum.repos.d /etc/anaconda.repos.d \
    && rm -f /etc/systemd/system/default.target \
    && ln -s /usr/lib/systemd/system/anaconda.target /etc/systemd/system/default.target \
    && rm -f /usr/lib/systemd/system-generators/systemd-gpt-auto-generator \
    && rm -f /usr/lib/systemd/system/autovt@.service \
    && ln -s /usr/lib/systemd/system/anaconda-shell@.service \
        /usr/lib/systemd/system/autovt@.service \
    && mkdir -p /usr/lib/systemd/logind.conf.d \
    && printf '%s\n' '[Login]' 'ReserveVT=2' \
        > /usr/lib/systemd/logind.conf.d/anaconda-shell.conf \
    && mkdir -p "$(realpath /root)" \
    && kernel="$(kernel-install list --json pretty \
        | jq -r '.[] | select(.has_kernel == true) | .version')" \
    && DRACUT_NO_XATTR=1 dracut --force --verbose --zstd --reproducible \
        --no-hostonly \
        --add anaconda \
        --include /usr/share/anaconda/andromeda-ci.ks /andromeda-ci.ks \
        --include /usr/share/anaconda/interactive-defaults.ks /interactive-defaults.ks \
        "/usr/lib/modules/${kernel}/initramfs.img" "${kernel}" \
    && mkdir -p /etc/systemd/user/pipewire.service.d \
        /etc/systemd/user/pipewire.socket.d \
    && printf '%s\n' '[Unit]' 'ConditionUser=' \
        > /etc/systemd/user/pipewire.service.d/allowroot.conf \
    && printf '%s\n' '[Unit]' 'ConditionUser=' \
        > /etc/systemd/user/pipewire.socket.d/allowroot.conf
